#!/bin/bash

load "$(dirname $BATS_TEST_DIRNAME)/stub"

log() {
  local str="$1"
  echo "$1" >> ./tmp
}

clear_stubs() {
    remove_stubs
}

stub() {
    add_stub "$@"
}

return_false() {
    read -d '' String <<"EOF"
#!/bin/bash

log() {
  local str=$1
  echo "$str" >> ./tmp
}

exit 1
EOF

    echo "${String}"
}

return_false_if() {
  read -d '' STRING <<EOF
#!/bin/bash

log() {
  local str=\$1
  echo "\$str" >> ./tmp
}

if [ "\$1" == "$1" ]; then
  exit 1
else
  exit 0
fi
EOF

  echo "${STRING}"
}
