#!/bin/bash

load "$(dirname $BATS_TEST_DIRNAME)/stub"

log() {
  local str="$1"
  echo "$1" >> ./tmp/debug.log
}

clear_stubs() {
    remove_stubs
}

stub() {
    add_stub "$@"
}

return_false() {
    read -d '' String <<"EOF"
#!/bin/bash

log() {
  local str=$1
  echo "$str" >> ./tmp/debug.log
}

exit 1
EOF

    echo "${String}"
}

return_true() {
    read -d '' String <<"EOF"
#!/bin/bash

log() {
  local str=$1
  echo "$str" >> ./tmp/debug.log
}

exit 0
EOF

    echo "${String}"
}

echo_value() {
  read -d '' STRING <<EOF
#!/bin/bash

echo "$1"
EOF

  echo "${STRING}"
}

return_false_if() {
  read -d '' STRING <<EOF
#!/bin/bash

log() {
  local str=\$1
  echo "\$str" >> ./tmp/debug.log
}

if [ "\$1" == "$1" ]; then
  exit 1
else
  exit 0
fi
EOF

  echo "${STRING}"
}

fixture_installed_versions() {

  read -d '' STRING <<EOF
#!/bin/bash

log() {
  local str=\$1
  echo "\$str" >> ./tmp/debug.log
}

echo "$XCODE_VERSIONS_DIRNAME/5.1/Xcode.app/Contents\n
$XCODE_VERSIONS_DIRNAME/6.1/Xcode.app/Contents\n
$XCODE_VERSIONS_DIRNAME/6.4/Xcode.app/Contents\n
$XCODE_VERSIONS_DIRNAME/7.1/Xcode.app/Contents"
EOF

  echo "${STRING}"
}
