#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

source "$(abs_dirname)/functions.sh"
if ! is_installed "xcode-select" ; then
  echo "exx: xcode-select command is not installed"
  exit 1
fi

if ! is_installed "PlistBuddy" ; then
  echo "exx: PlistBuddy command is not available. Is /usr/bin/libexec in you PATH ?"
  exit 1
fi

if ! is_installed "shml" ; then
  echo "exx: shml command is not available. see https://maxcdn.github.io/shml/getting-started/#Install"
  exit 1
fi

libexec_path="$(abs_dirname "$0")"
export _EXX_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec exx-help
  ;;
* )
  command_path="$(command -v "exx-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "exx: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
