#!/usr/bin/env bash
# Usage: exx ls
# Summary: List all installed Xcode subfolders

source "$_EXX_ROOT/functions.sh"

LATEST=$(get_latest_version)

VERSIONS=("  $LATEST\n")
INSTALLED=$(get_installed_versions)

for VERSION in $INSTALLED; do
  VERSIONS+="  $VERSION\n"
done

echo "$VERSIONS"
