#!/usr/bin/env bash
# Usage: exx ls
# Summary: List all installed Xcode subfolders

source "$_EXX_ROOT/functions.sh"
source "$(require_path "shml")"

LATEST=$(get_latest_version)
CURRENT=$(get_current_version)

if [ "$LATEST" == "$CURRENT" ]; then
  VERSIONS=" $(echo $(fgc green)$(icon check)$(fgc end)) $(attribute bold "$LATEST")$(attribute end)"
else
  VERSIONS="   $LATEST"
fi

INSTALLED=$(get_installed_versions)

for VERSION in $INSTALLED; do
  V=$(printf "$VERSION")
  VERSIONS="${VERSIONS}\n   ${V}"
done

printf "$VERSIONS"
