#!/usr/bin/env sh
# Usage: exx info
# Summary: Returns the current xcode version

CHECK="\033[32m✔\033[0m "
LATEST_VERSION=`/usr/libexec/PlistBuddy /Applications/Xcode.app/Contents/version.plist -c "Print CFBundleShortVersionString"`

echo $CHECK $LATEST_VERSION
