#!/usr/bin/env sh
# Usage: exx switch [version]
# Summary: Switch from one version of Xcode to another

if [ -z $1 ]; then
    echo "  ⛔ \033[31m Missing XCode version\033[0m"
    exit 1
fi

CURRENT=`xcode-select -p | cut -d\/ -f 4`
if [ "$CURRENT" == "Contents" ]; then
  CURRENT=`/usr/libexec/PlistBuddy /Applications/Xcode.app/Contents/version.plist -c "Print CFBundleShortVersionString"`
fi

if [ "$1" == "$CURRENT" ]; then
  echo "  \033[32m✔\033[0m Current Xcode version is already \033[96m$1\033[0m"
  exit 0
fi

echo "Switching version from \033[96m$CURRENT\033[0m to \033[31m$1\033[0m"
sudo xcode-select --switch /Applications/Xcode/$1/Xcode.app/Contents/Developer

if [ $? -ne 0 ]; then
    CURRENT=`xcode-select -p | cut -d\/ -f 4`
    echo "  ⛔ \033[31mSetting failed\033[0m"
    echo "  Xcode version is \033[31m$CURRENT\033[0m"
    exit 2
fi

echo "  \033[32m✔\033[0m Xcode version switched successfully"

